### PR TITLE
[neptune] Update submodules

### PR DESCRIPTION
**Pull request by jenkins-sociomantic**
This PR has been automatically created by *neptune-autopr* and
updates the following submodules:

* **makd** from version **v2.1.3** to version **v2.2.0** ([Release notes](https://github.com/sociomantic-tsunami/makd/releases/tag/v2.2.0), [Changed commits](https://github.com/sociomantic-tsunami/makd/compare/v2.1.3...v2.2.0))
* **ocean** from version **v3.5.11** to version **v3.5.12** ([Release notes](https://github.com/sociomantic-tsunami/ocean/releases/tag/v3.5.12), [Changed commits](https://github.com/sociomantic-tsunami/ocean/compare/v3.5.11...v3.5.12))

You can modify this behavior using your `.neptune.yml` file
as described in the [documentation](https://github.com/sociomantic-tsunami/neptune/blob/master/doc/neptune-metadata.rst#automatic-update-prs).

### CODE REVIEW

**Review by jens-mueller-sociomantic — DISMISSED** [review]

**Comment by joseph-wakeling-sociomantic** [comment]
I think we should probably close this PR in favour of a manual one that updates to a much more recent ocean.  We're still in v0.x.y release series, so we can do this without an issue.

**Comment by joseph-wakeling-sociomantic** [comment]
I'll close once such an update is complete.

**Review by joseph-wakeling-sociomantic — APPROVED** [review]
I guess this is fine to take in.  I'll do the manual ocean update afterwards.

**Comment by jens-mueller-sociomantic** [comment]
Why didn't we get the beaver update here?

**Comment by joseph-wakeling-sociomantic** [comment]
Good question.

**Comment by mathias-baumann-sociomantic** [comment]
If it was a minor update, you wouldn't get it unless you change your defaults to accept minor updates.

Because this is marked as a library, it receives only patch updates automatically. The motivation behind this is, that we want libraries to have older dependencies so that the applications using them aren't forced to update. Basically, keeping the consequences of updating as low as possible for the things depending on the library

**Comment by jens-mueller-sociomantic** [comment]
We have configured it to receive minor updates for `makd` and `beaver` (see https://github.com/sociomantic-tsunami/dmxnet/blob/v0.x.x/.neptune.yml#L3-L7).

**Comment by joseph-wakeling-sociomantic** [comment]
Right, we'd expect the library default to be respected in general, but not where we explicitly specify an override.

**Comment by joseph-wakeling-sociomantic** [comment]
If there is a hard policy decision here, that's fine, but please let us know.  I would expect per-submodule overrides to be supported (and note that our use case is entirely valid: treating CI differently from actual code dependencies).

**Comment by mathias-baumann-sociomantic** [comment]
Whatever you configured should work. Could you write exactly what you expected to happen and what actually happened? Including the times it should have happened? I can then investigate.

**Comment by joseph-wakeling-sociomantic** [comment]
What we expected to happen was that we should get minor-release patches for makd and beaver (since there are more recent releases than the ones currently used by dmxnet).

The PR to update the autopr settings was merged a week ago: https://github.com/sociomantic-tsunami/dmxnet/pull/62 so we'd expect to have received such PRs on at least one day since then.  But we never got any.

**Comment by mathias-baumann-sociomantic** [comment]
I take it with the latest changes those problems are fixed now (marking beaver as library and makd being rather recent)

**Comment by joseph-wakeling-sociomantic** [comment]
We got an update PR, yes.  Thanks! :-)

**Pull request merged**
