### PR TITLE
Upgrade to v3 of dlang dockerfile

### PR DESCRIPTION
**Pull request by joseph-wakeling-sociomantic**
This upgraded dockerfile should come with explicitly pinned versions of various packages (e.g. D compilers).  This should make for a more stable testing environment.

### CODE REVIEW

**Comment by joseph-wakeling-sociomantic** [comment]
@leandro-lucarella-sociomantic you might want to confirm that I've correctly understood the impact of this upgrade ;-)

**Review by leandro-lucarella-sociomantic — APPROVED** [review]
Yeah, shocking and breaking changes!

**Comment by leandro-lucarella-sociomantic** [comment]
(you might want to update beaver too if you didn't, it shouldn't be actually necessary unless you are using test docker images though)

**Comment by joseph-wakeling-sociomantic** [comment]
@leandro-lucarella-sociomantic already done, the PR was there less than 10 minutes after your release email ;-) https://github.com/sociomantic-tsunami/dmxnet/pull/26

Just for my understanding: can we now explicitly pin packages ourselves in our own dockerfile definitions?

**Comment by leandro-lucarella-sociomantic** [comment]
Yes, you could always do that actually. But when you install your own packages you can chose the version, this is only useful for base images, where a user could do a `full-upgrade` and screw everything.

**Comment by joseph-wakeling-sociomantic** [comment]
@leandro-lucarella-sociomantic gotcha.  Thanks for the clarification :-)

**Pull request merged**
