### PR TITLE
Update makd from v2.0.1 to v2.1.1

### PR DESCRIPTION
**Pull request by joseph-wakeling-sociomantic**
* submodules/makd v2.0.1(d735c1d)...v2.1.1(271b317) (5 commits)
  > Merge tag v1.11.1 into v2.1.x v1.11.1
  > Merge tag v2.0.3 into v2.1.x v2.0.3
  > Merge tag v1.11.0 into v2.x.x Features --------
  > Merge tag v2.0.2 into v2.x.x v2.0.2
  > Merge tag 'v2.0.1' into v2.x.x

### CODE REVIEW

**Comment by joseph-wakeling-sociomantic** [comment]
Rebased on latest v0.x.x branch.

**Comment by joseph-wakeling-sociomantic** [comment]
Let's update this to v2.1.1, since that's now released with a fix for the v2.1.0 bug.

**Comment by joseph-wakeling-sociomantic** [comment]
Updated to v2.1.1.  Ready for review.

**Comment by jens-mueller-sociomantic** [comment]
LGTM. But PR title needs to be changed and also the first comment.

**Comment by joseph-wakeling-sociomantic** [comment]
Whoops.  Updated.

**Review by jens-mueller-sociomantic — APPROVED** [review]

**Pull request merged**
