### PR TITLE
Advance ocean from v3.5.12 to v4.2.1

### PR DESCRIPTION
**Pull request by joseph-wakeling-sociomantic**
ocean v3.5.12(d49e328e)...v4.2.1(adaa0114)
    
Release notes: https://github.com/sociomantic-tsunami/ocean/releases/tag/v4.2.1
Changed commits: https://github.com/sociomantic-tsunami/ocean/compare/v3.5.12...v4.2.1

This brings dmxnet's ocean dependency up to date with the latest major release series.  This is a breaking change, but a tolerable one given that we are still in the v0.x.y release series.

### CODE REVIEW

**Comment by jens-mueller-sociomantic** [comment]
Just to verify: This requires downstream users to be on ocean v4.1.6 which alright I'll guess.

**Comment by joseph-wakeling-sociomantic** [comment]
Yes.  Note that semver explicitly allows us to make this sort of breaking change in a minor release from the v0.x.y series.

**Comment by joseph-wakeling-sociomantic** [comment]
Updated to the just-release v4.2.0.

**Review by jens-mueller-sociomantic — APPROVED** [review]

**Review by jens-mueller-sociomantic — CHANGES_REQUESTED** [review]
There is a `v4.2.1` out now which should be used instead I think.

**Comment by joseph-wakeling-sociomantic** [comment]
Updated.

**Comment by joseph-wakeling-sociomantic** [comment]
BTW, normally, if something like this was passing, I'd suggest just taking it in and letting neptune-autopr take care of the patch releases (we might as well rely on automation for what we can).  But since it looks like there was a CI snafu anyway, might as well update ;-)

**Review by jens-mueller-sociomantic — APPROVED** [review]

**Pull request merged**
